BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS urls (
			id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::text UNIQUE,
			key VARCHAR(100),
			full_uri VARCHAR(1500) UNIQUE,
			users TEXT[],
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);

COMMIT;